services:
  mysql:
    image: mysql:9.1.0
    container_name: cinetopia-mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cinetopia
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: .
    container_name: cinetopia-django
    volumes:
      - .:/backend
      - static_volume:/backend/static
      - media_volume:/backend/media
    env_file:
      - ./cinetopia/.env
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn -b 0.0.0.0:8000 cinetopia.wsgi:application"
    ports:
      - "8000:8000"
    networks:
      - mysql_network

volumes:
  mysql_data:
  static_volume:
  media_volume:

networks:
  mysql_network:
    driver: bridge