# Generated by Django 5.1.7 on 2025-05-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='countries',
        ),
        migrations.AlterUniqueTogether(
            name='moviegenre',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='moviegenre',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='MovieCountry',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
