# Generated by Django 5.1.7 on 2025-05-20 14:58

from django.db import migrations

from cinema.models import Genre


def init_genres(*args, **kwargs):
    genres = [
        Genre(name='Ужасы'),
        Genre(name='Фантастика'),
        Genre(name='Фэнтези'),
        Genre(name='Боевик'),
        Genre(name='Триллер'),
        Genre(name='Драма'),
        Genre(name='Комедия'),
        Genre(name='Мелодрама'),
        Genre(name='Детектив'),
        Genre(name='Криминал'),
        Genre(name='Приключения'),
        Genre(name='Вестерн'),
        Genre(name='Исторический'),
        Genre(name='Биографический'),
        Genre(name='Военный'),
        Genre(name='Музыкальный'),
        Genre(name='Мюзикл'),
        Genre(name='Семейный'),
        Genre(name='Детский'),
        Genre(name='Мультфильм'),
        Genre(name='Аниме'),
        Genre(name='Документальный'),
        Genre(name='Спортивный'),
        Genre(name='Короткометражный'),
        Genre(name='Артхаус'),
        Genre(name='Катастрофа'),
        Genre(name='Мистика'),
        Genre(name='Сюрреализм')
    ]
    Genre.objects.bulk_create(genres)

class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_movie_countries_movie_genres'),
    ]

    operations = [
        migrations.RunPython(init_genres)
    ]
