# Generated by Django 5.1.7 on 2025-06-01 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('currency', models.CharField(choices=[('RUB', '₽'), ('USD', '$'), ('EURO', '€')], default='RUB', max_length=10)),
                ('category', models.CharField(choices=[('movie', 'Фильм'), ('subscription', 'Подписка'), ('merch', 'Мерч'), ('bonus', 'Бонусные материалы')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
